name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia 'main' al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Configurar JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Compilar y ejecutar pruebas
      run: |
        mvn clean test

    - name: Crear reporte Allure
      run: |
        mvn allure:report

    - name: Subir resultados de Allure como un artefacto
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results
